### ISSUE TITLE
DeepRecommender with Movielens dataset

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/sciblog_support#60]
there is a script to transform the movielens data: https://github.com/NVIDIA/DeepRecommender/blob/master/data_utils/movie_lense_data_converter.py

data: `wget http://files.grouplens.org/datasets/movielens/ml-20m.zip`

To compute the dataset:
`python data_utils/movie_lense_data_converter.py /datadrive/movielens/ml-20m/ratings.csv movielens`

I had to add `.txt` at the end and move each file to an independent folder

then finally: `python run.py --gpu_ids 0 --path_to_train_data movielens/train --path_to_eval_data movielens/val --hidden_layers 512,512,1024 --non_linearity_type selu --batch_size 128 --logdir model_movielens --drop_prob 0.8 --optimizer momentum --lr 0.005 --weight_decay 0 --aug_step 1 --noise_prob 0 --num_epochs 1 --summary_frequency 1000`
I get an error:
```bash
Loading training data
Data loaded
Total items found: 138493
Vector dim: 20668
Loading eval data
Traceback (most recent call last):
  File "run.py", line 236, in <module>
    main()
  File "run.py", line 116, in main
    item_id_map=data_layer.itemIdMap)
  File "/home/hoaphumanoid/notebooks/repos/DeepRecommender/reco_encoder/data/input_layer.py", line 48, in __init__
    value = minor_map[int(parts[self._minor_ind])]
KeyError: 18223
```

**Comment by miguelgfierro** [comment]
```bash
head movielens/val/movielens.valid.txt 
0       65      4.0
0       174     4.0
0       76      4.0
0       169     3.5
0       151     4.0
0       71      4.0
0       102     4.0
0       167     4.0
0       121     4.0
0       97      4.0

 tail movielens/val/movielens.valid.txt 
131070  1708    3.0
131070  1401    4.0
131070  404     2.0
131070  446     3.0
131070  681     5.0
131070  382     2.0
131070  408     5.0
131070  2128    3.0
131070  1336    3.0
131070  648     4.0

head Netflix/NF_VALID/nf.valid.txt 
262144  524     5.0
262144  15743   4.0
262144  4597    5.0
262144  5891    4.0
262144  6727    2.0
262144  9189    2.0
262144  11579   5.0
262144  13716   3.0
262144  15474   5.0
262144  15644   5.0

 tail Netflix/NF_VALID/nf.valid.txt 
262136  14277   3.0
262136  14735   4.0
262136  15236   4.0
262136  16033   3.0
262136  16067   2.0
262136  16222   5.0
262136  16581   4.0
262141  5432    5.0
324718  1621    4.0
324718  2268    2.0

```

**Comment by miguelgfierro** [comment]
Finally not implemented
