### ISSUE TITLE
issue with websockets and namespace

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/sciblog_support#87]
I get the following error in https://github.com/miguelgfierro/sciblog_support/commit/fefd7997966d7eaf5c7484fef9ebb45b55d4ce99:
```bash

Value predicted: 1.0
New location: {'title': 'Ipiales', 'latitude': 0.830374368, 'longitude': -77.64999964}
Traceback (most recent call last):
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/miguel/run3x/sciblog_support/Intro_to_Fraud_Detection/api.py", line 80, in predict_map
    emit('map_update', location)
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/flask_socketio/__init__.py", line 688, in emit
    namespace = flask.request.namespace
  File "/Users/miguel/anaconda3/envs/fraud/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'namespace'
```

**Comment by miguelgfierro** [comment]
I had to add socketio.emit('map_update', location, broadcast=True) instead of emit(...) because I was not inside @socketio decorator
